export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"
export const USER_DETAILS_RESET = "USER_DETAILS_RESET"

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST"
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS"
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL"
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET"

export const USER_SINGLE_USER_TRANSACTIONS_REQUEST =
  "USER_SINGLE_USER_TRANSACTIONS_REQUEST"
export const USER_SINGLE_USER_TRANSACTIONS_SUCCESS =
  "USER_SINGLE_USER_TRANSACTIONS_SUCCESS"
export const USER_SINGLE_USER_TRANSACTIONS_FAIL =
  "USER_SINGLE_USER_TRANSACTIONS_FAIL"
export const USER_SINGLE_USER_TRANSACTIONS_RESET =
  "USER_SINGLE_USER_TRANSACTIONS_RESET"

export const USER_CREATE_TRANSACTIONS_REQUEST =
  "USER_CREATE_TRANSACTIONS_REQUEST"
export const USER_CREATE_TRANSACTIONS_SUCCESS =
  "USER_CREATE_TRANSACTIONS_SUCCESS"
export const USER_CREATE_TRANSACTIONS_FAIL = "USER_CREATE_TRANSACTIONS_FAIL"

export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL"
export const USER_LIST_RESET = "USER_LIST_RESET"

export const USER_GET_BY_ID_REQUEST = "USER_GET_BY_ID_REQUEST"
export const USER_GET_BY_ID_SUCCESS = "USER_GET_BY_ID_SUCCESS"
export const USER_GET_BY_ID_FAIL = "USER_GET_BY_ID_FAIL"
export const USER_GET_BY_ID_RESET = "USER_GET_BY_ID_RESET"

export const USER_TRANSACTION_BY_ID_REQUEST = "USER_TRANSACTION_BY_ID_REQUEST"
export const USER_TRANSACTION_BY_ID_SUCCESS = "USER_TRANSACTION_BY_ID_SUCCESS"
export const USER_TRANSACTION_BY_ID_FAIL = "USER_TRANSACTION_BY_ID_FAIL"

export const UPDATE_USER_TRANSACTION_BY_ID_REQUEST =
  "USER_TRANSACTION_BY_ID_REQUEST"
export const UPDATE_USER_TRANSACTION_BY_ID_SUCCESS =
  "USER_TRANSACTION_BY_ID_SUCCESS"
export const UPDATE_USER_TRANSACTION_BY_ID_FAIL = "USER_TRANSACTION_BY_ID_FAIL"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

export const USER_REFERRAL_BY_ID_REQUEST = "USER_REFERRAL_BY_ID_REQUEST"
export const USER_REFERRAL_BY_ID_SUCCESS = "USER_REFERRAL_BY_ID_SUCCESS"
export const USER_REFERRAL_BY_ID_FAIL = "USER_REFERRAL_BY_ID_FAIL"
